# Generated by Django 5.2.1 on 2025-05-28 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social Principal')),
                ('razon_social2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social Secundaria')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT Empresa')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('tipo_vehiculo', models.CharField(max_length=255, verbose_name='Tipo de Vehículo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo_transmision', models.CharField(max_length=50, verbose_name='Tipo de Transmisión')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo', 'patente'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario_completo', models.CharField(max_length=255, verbose_name='Nombre Completo del Usuario')),
                ('razon_social_empresa', models.CharField(max_length=255, verbose_name='Razón Social Empresa Asignada')),
                ('razon_social2_empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social Secundaria Empresa')),
                ('rut_empresa', models.CharField(max_length=20, verbose_name='RUT Empresa Asignada')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sistema', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'ordering': ['nombre_usuario_completo'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_inicio_reserva', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin_reserva', models.TimeField(verbose_name='Hora de Fin')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_realizadas', to='agendamiento.usuariosistema', verbose_name='Usuario que Reserva')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='agendamiento.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_reserva', 'hora_inicio_reserva', 'vehiculo'],
                'unique_together': {('vehiculo', 'fecha_reserva', 'hora_inicio_reserva')},
            },
        ),
    ]
